### ISSUE TITLE
Uncaught `SocketTimeoutException`

### ISSUE THREAD

**Issue by gnarea** [relaycorp/awala-endpoint-android#359]
We recently got the following exception from a Nexus 5X:

```
Fatal Exception: java.net.SocketTimeoutException: sent ping but didn't receive pong within 5000ms (after 1 successful ping/pongs)
       at okhttp3.internal.ws.RealWebSocket.writePingFrame$okhttp(RealWebSocket.kt:563)
       at okhttp3.internal.ws.RealWebSocket$initReaderAndWriter$lambda$3$$inlined$schedule$1.runOnce(TaskQueue.kt:219)
       at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
       at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
       at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

I don't know what the conditions were and don't have access to the Android gateway logs.

More info: https://console.firebase.google.com/project/letro-android/crashlytics/app/android:tech.relaycorp.letro/issues/c2dfec37a5d278b2f4c4abef0ed18165?time=last-seven-days&sessionEventKey=656D9EBF024F000110F898FB15F588E7_1887118058561338754

**Comment by sdsantos** [comment]
Looks like a duplicate from https://github.com/relaycorp/awala-poweb-jvm/issues/302
But it adds some more information to the investigation.

**Comment by gnarea** [comment]
Ah, yeah, good catch
