### ISSUE TITLE
Upgrading the Android gateway may cause apps using this library to crash

### ISSUE THREAD

**Issue by gnarea** [relaycorp/awala-endpoint-android#75]
If an Awala app is collecting parcels when the gateway is upgraded, it'll crash with the following:

```
2021-04-05 14:58:44.538 8544-8883/tech.relaycorp.ping E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: tech.relaycorp.ping, PID: 8544
    tech.relaycorp.relaynet.bindings.pdc.ServerConnectionException: Connection was closed abruptly
        at tech.relaycorp.poweb.PoWebClient.wsConnect$poweb(PoWebClient.kt:290)
        at tech.relaycorp.poweb.PoWebClient$wsConnect$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
        at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

I think we should wrap `ServerConnectionException`s around an exception provided by this library, so that app developers can handle such exceptions.

**Comment by sdsantos** [comment]
I wasn't able to reproduce the issue. The only place that exception is thrown is from inside Awaladroid `ReceiveMessages#collectParcels` and we're already handling `ServerException` there, a superclass of `ServerConnectionException` of the crash log. And, that scenario is covered by a test.

We only collect parcels when we're notified on the ping app. And this call should be safe `GatewayClient.receiveMessages().collect(receivePong::receive)` since that only subscribes to a stream of parcels that we receive, but it's not the stream collecting the parcels. Since it's disconnected from the stuff that might fail when connecting with the Gateway, developers won't need to re-subscribe to it.
